name: check

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-20.04
    permissions:
      statuses: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1

      - name: Install packages
        run: opam install dune memtrace

      - name: Make programs
        run: |
          eval $(opam env) && find . -maxdepth 1 -type d -not -path "." -not -path "./doc" -not -path "./.git*" -exec make -C '{}' \;

      - name: Report elapsed time
        run: |
          RES=`./check`
          echo $RES
          COMPARE_ELAPSED= `$RES | sed -n -e  '1p' | cut -d " " -f2`
          EMPTY_ELAPSED= `$RES | sed -n -e  '2p' | cut -d " " -f2`
          EQUALITY_ELAPSED= `$RES | sed -n -e  '3p' | cut -d " " -f2`
          FILE-IO_ELAPSED= `$RES | sed -n -e  '4p' | cut -d " " -f2`
          LIST_ELAPSED= `$RES | sed -n -e  '5p' | cut -d " " -f2`
          REGEXP_ELAPSED= `$RES | sed -n -e  '6p' | cut -d " " -f2`
          SERIALIZE_GEN_ELAPSED= `$RES | sed -n -e  '7p' | cut -d " " -f2`
          SERIALIZE_READ_ELAPSED= `$RES | sed -n -e  '8p' | cut -d " " -f2`
          STRING_ELAPSED= `$RES | sed -n -e  '9p' | cut -d " " -f2`
          TAIL-RECURSION_ELAPSED= `$RES | sed -n -e  '10p' | cut -d " " -f2`

          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${COMPARE_ELAPSED}"'","context":"check/compare"}'
