name: check

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-20.04
    permissions:
      statuses: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v3
        env:
          cache-name: cache-opam
        with:
          path: |
            ~/.opam
            ./_opam
          key: ${{ env.cache-name }}-build-${{ hashFiles('README.md') }}
          restore-keys: |
            ${{ env.cache-name }}-build-${{ hashFiles('README.md') }}
            ${{ env.cache-name }}-build-

      - name: Install packages
        run: opam install dune memtrace

      - name: Make programs
        run: |
          eval $(opam env) && find . -maxdepth 1 -type d -not -path "." -not -path "./doc" -not -path "./.git*" -exec make -C '{}' \;

      - name: Report elapsed time
        run: |
          RES="$(./check)"
          echo $RES
          COMPARE_ELAPSED=`echo $RES | cut -d " " -f2,3`
          EMPTY_ELAPSED=`echo $RES | cut -d " " -f5,6`
          EQUALITY_ELAPSED=`echo $RES | cut -d " " -f8,9`
          FILE_IO_ELAPSED=`echo $RES | cut -d " " -f11,12`
          LIST_ELAPSED=`echo $RES | cut -d " " -f14,15`
          REGEXP_ELAPSED=`echo $RES | cut -d " " -f17,18`
          SERIALIZE_GEN_ELAPSED=`echo $RES | cut -d " " -f20,21`
          SERIALIZE_READ_ELAPSED=`echo $RES | cut -d " " -f23,24`
          STRING_ELAPSED=`echo $RES | cut -d " " -f26,27`
          TAIL_RECURSION_ELAPSED=`echo $RES | cut -d " " -f29,30`

          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${COMPARE_ELAPSED}"'","context":"check/compare"}'
          
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${EMPTY_ELAPSED}"'","context":"check/empty"}'
            
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${EQUALITY_ELAPSED}"'","context":"check/equality"}'
            
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${FILE_IO_ELAPSED}"'","context":"check/file_io"}'
            
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${LIST_ELAPSED}"'","context":"check/list"}'
            
            curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${REGEXP_ELAPSED}"'","context":"check/regexp"}'
            
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${SERIALIZE_GEN_ELAPSED}"'","context":"check/serialize_gen"}'
            
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${SERIALIZE_READ_ELAPSED}"'","context":"check/serialize_read"}'
            
  
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${STRING_ELAPSED}"'","context":"check/string"}'

          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${TAIL_RECURSION_ELAPSED}"'","context":"check/tail_recursion"}'


